export {default as App} from './App/App'
export {default as Home} from './Home'
export {default as Pages} from './Pages'
export {default as Page} from './Page'
export {default as AboutUs} from './AboutUs'